### ISSUE TITLE
QA Adjustment of the public library Part 2

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-cli-plugin-sections#20]
You can use a.sarkis+cnameprojectnov@eweev.com / Goldman31 to login to the BO and then access the site

<details>
<summary> Layout </summary>

- [x] The layout is not working correctly, if you follow the below steps you will see that nothing is display on the page
- Access the Home page in edit mode that is standard layout
- Modify it to top right left bottom layout
- Save the page
- Access page page1
- Go back to the home page, you will see that nothing is showing, you need to change back the layout to Standard to have the sections showing

**IMPORTANT: Please to write an automated test for this before fixing the problem and mention in the issue that it is done**

</details>

<details>
<summary> Preview </summary>

- [x] The preview of the suggested articles do not contain images and it should
- [x] All the uninstalled sections have no preview... why ? they should have
- [ ] For the Author details, if you add the social medias like I mentioned , the preview needs to be updated as well

</details>

<details>
<summary> Simple menu section </summary>

- [x] The pages listing in the form , let's have the page path in the left not centered, like other sections ( I added a menu section in the home page )

<img width="495" alt="Screenshot 2024-11-07 at 14 34 11" src="https://github.com/user-attachments/assets/5128700e-8da2-4c41-8e86-e01c97a778a3">

- [x] If I have selected a page then I should not be able to enter a URL in Other, so we need that in the page listing we have an option Other and if I select it then the Other fields shows, else it is hidden
- [x] Clicking an Anchor is not copying the anchor, this is not specific to simple menu but as I wanted to copy one while working on it I added the point here
- [x] When I select a page in the listing I can no more unselect it which is wrong
- [x] If for a menu I have chosen other when I hover on it on the vue mode there is not a hand showing it is a link which is 
wrong
- [x] We need to be able add a menu to change language
- [x] We need for each link a field to add one or more classes, it is a text field, and those will be used in the css file to have the correct styling for those menus
- Add a description for the class field
- [x] For the field Other we need a description for each kind of link we can add and the behavior that it will have
- [ ] We need a hidden field that will be under a label Advanced that you can expand and when you expand it you will have possibility to enter options and for each one an attribute and its value, like for example target = _blank, check, do what is more appropriate to have it.
- Add a description for the Options field
- [x] We need an additional label in the top Menu Label that  can be empty and as well fo it the Css classes field that will allow when using them to change the style of the whole menu so if we are using sections css have it or like the header of sections, or like the footer of sections

</details>

<details>
<summary> Interactive display </summary>

- [x] When you have an interactive display section with video, you cannot drag and drop it, even if you try to move it , it remains to its place. It happens that sometime it moves but more often it remains to its place

</details>

<details>
<summary> Plans sections </summary>

- [x] Use the section used in geeks website and not in section
- [x] Make sure the form follow the same rules as on geeks website
- [x] The links in the bottom are not aligned and they should be

</details>

<details>
<summary> Blogs sections </summary>

- [x] For the Author details, Copy link should be a button, like this it take the selector of the button when choosing a css
- [x] More of this the social media links aren't part of the author details vue section ( Ref to the one of Maiori ), because they are not there ?

<img width="1539" alt="Screenshot 2024-11-07 at 15 04 45" src="https://github.com/user-attachments/assets/d751c77b-b401-4281-8b59-d4cb4db0289a">

</details>

<details>
<summary> general </summary>

- [x] For any section we must not have H1 in the HTML code

</details>

### **Acceptance testing**

<details>
<summary> Layout </summary>

- [x] The layout is not working correctly, if you follow the below steps you will see that nothing is display on the page
- Access the Home page in edit mode that is standard layout
- Modify it to top right left bottom layout
- Save the page
- Access page page1
- Go back to the home page, you will see that nothing is showing, you need to change back the layout to Standard to have the sections showing

**Make sure automated test covers this point**

</details>

<details>
<summary> Preview </summary>

- [x] The preview of the suggested articles do not contain images and it should
- [x] All the uninstalled sections have no preview... why ? they should have
- [x] For the Author details, if you add the social medias like I mentioned , the preview needs to be updated as well

</details>

<details>
<summary> Simple menu section </summary>

- [x] The pages listing in the form , let's have the page path in the left not centered, like other sections ( I added a menu section in the home page )

<img width="495" alt="Screenshot 2024-11-07 at 14 34 11" src="https://github.com/user-attachments/assets/5128700e-8da2-4c41-8e86-e01c97a778a3">

- [x] If I have selected a page then I should not be able to enter a URL in Other, so we need that in the page listing we have an option Other and if I select it then the Other fields shows, else it is hidden
- [x] Clicking an Anchor is not copying the anchor, this is not specific to simple menu but as I wanted to copy one while working on it I added the point here
- [x] When I select a page in the listing I can no more unselect it which is wrong
- [x] If for a menu I have chosen other when I hover on it on the vue mode there is not a hand showing it is a link which is 
wrong
- [x] We need to be able add a menu to change language
- [x] We need for each link a field to add one or more classes, it is a text field, and those will be used in the css file to have the correct styling for those menus and make sure there is a description
- [x] For the field Other we need a description for each kind of link we can add and the behavior that it will have
- [ ] We need a hidden field that will be under a label Advanced that you can expand and when you expand it you will have possibility to enter options and for each one an attribute and its value, like for example target = _blank, check, do what is more appropriate to have it. And make sure there is a description
- [x] We need an additional label in the top Menu Label that  can be empty and as well fo it the Css classes field that will allow when using them to change the style of the whole menu so if we are using sections css have it or like the header of sections, or like the footer of sections

</details>

<details>
<summary> Interactive display </summary>

- [ ] When you have an interactive display section with video, you cannot drag and drop it, even if you try to move it , it remains to its place. It happens that sometime it moves but more often it remains to its place

</details>

<details>
<summary> Plans sections </summary>

- [x] Use the section used in geeks website and not in section
- [x] Make sure the form follow the same rules as on geeks website
- [x] The links in the bottom are not aligned and they should be

</details>

<details>
<summary> Blogs sections </summary>

- [x] For the Author details, Copy link should be a button, like this it take the selector of the button when choosing a css
- [x] More of this the social media links aren't part of the author details vue section ( Ref to the one of Maiori ), because they are not there ?

<img width="1539" alt="Screenshot 2024-11-07 at 15 04 45" src="https://github.com/user-attachments/assets/d751c77b-b401-4281-8b59-d4cb4db0289a">

</details>

<details>
<summary> general </summary>

- [x] For any section we must not have H1 in the HTML code

</details>

**Comment by mahfouzhseineweev** [comment]
> All the uninstalled sections have no preview... why ? they should have

They are not just uninstalled from the project. They are also removed from the host project code, and so they have no forms or views. This is why they can not have a preview

> We need to be able add a menu to change language

Can't you simply add a menu that redirect to`/` in english and to `/fr` in french ?

> We need a hidden field that will be under a label Advanced that you can expand and when you expand it you will have possibility to enter options and for each one an attribute and its value, like for example target = _blank, check, do what is more appropriate to have it.
Add a description for the Options field

I didn't get this one, we already have a management for the links that automatically handle the anchors, external links, internal links. So what is this for ? 

Also these options can not have dynamic keys, the keys like `target` has to be predefined and only the values can be dynamic


@akramsarkis  NOTE: Let us move the points about the css fixes to this issue https://gl.eweev.com/eweev/geeks/meta-sections/-/issues/26 
Which are the CSS of the plans, QAs, BLOGs, menus etc...

**Comment by akramsarkis** [comment]
> > All the uninstalled sections have no preview... why ? they should have
> 
> They are not just uninstalled from the project. They are also removed from the host project code, and so they have no forms or views. This is why they can not have a preview
> 
> > We need to be able add a menu to change language
> 
> Can't you simply add a menu that redirect to`/` in english and to `/fr` in french ?
> 
> > We need a hidden field that will be under a label Advanced that you can expand and when you expand it you will have possibility to enter options and for each one an attribute and its value, like for example target = _blank, check, do what is more appropriate to have it.
> > Add a description for the Options field
> 
> I didn't get this one, we already have a management for the links that automatically handle the anchors, external links, internal links. So what is this for ?
> 
> Also these options can not have dynamic keys, the keys like `target` has to be predefined and only the values can be dynamic
> 
> @akramsarkis NOTE: Let us move the points about the css fixes to this issue https://gl.eweev.com/eweev/geeks/meta-sections/-/issues/26 Which are the CSS of the plans, FAQ, BLOGs, menus etc...

1) Concerning the uninstalled sections that are on inventory, this is a request from Julien, so you need to check with him

2) Well this as well a request from julien, now if it works by adding such menu this is fine, but i must change the language indeed, is it the case ?

3) For the options it is a request for julien, he told me that showing you the example you will understand what is needed, but from what I got , it is to give possibility like the example I gave is to open in a new tab or not the link you are using, concerning he dynamic point please to check with Julien

4) For the FAQ the points I can move are the one for plans and FAQ, the others are to to precise how it work, i mean like blogs it is just to saye that when using css then it will change, for the menu it is just to indicate that those classes you will add will be used when using the CSS

**Comment by mahfouzhseineweev** [comment]
## Report regarding the automated test point of the library

I have made a good progress on this point.

* test-utils and jest were not setup correctly on the library so I had to do the setup and configuration for it.

* With the help of ChatGpt, I am exploring the correct way to write the test scenario needed to cover this specific case as a start

* The test file is still not working as expected, and I reached a point problem where the fetch hook is not called and returning an undefined error when running the test

*  Here is the test component code I have so far:

```js
import { shallowMount } from '@vue/test-utils'
import SectionsMain from '../lib/src/components/Sections/index.vue'

jest.mock('@geeks.solutions/vue-components/components/AutoComplete.vue', () => ({
  name: 'AutoComplete',
  render: () => null
}));

describe('SectionsMain', () => {
  test('calls initializeSections and computeLayoutData in fetch()', async () => {
    // Create a spy for both methods
    const initializeSectionsSpy = jest.spyOn(SectionsMain.methods, 'initializeSections')
    const computeLayoutDataSpy = jest.spyOn(SectionsMain.methods, 'computeLayoutData')

    // Mount the component
    const wrapper = shallowMount(SectionsMain, {
      mocks: {
        // Mock any dependencies like $axios or $store if they are used in fetch
        $sections: {
          cname: true
        }
      }
    })

    // Manually call the fetch method
    await wrapper.vm.fetch()

    // Check if both methods were called
    expect(initializeSectionsSpy).toHaveBeenCalled()
    expect(computeLayoutDataSpy).toHaveBeenCalled()

    // Optionally, check if initializeSections is called with the expected argument
    // Example: expect(initializeSectionsSpy).toHaveBeenCalledWith(expectedResponse)

    // Clean up the spies
    initializeSectionsSpy.mockRestore()
    computeLayoutDataSpy.mockRestore()
  })
})
```

* I expect to be done with the test with one or 2 more Timebox issues

**Comment by mahfouzhseineweev** [comment]
@jfayad 

1) Layout 0.25h to fix the problem (For the automated test I did a 1h Timebox and wrote my report above)
2) 0.5h without the uninstalled sections point as it is not feasible
3) 1.25h without the options point that is not clear
4) 0.25h
5) 1h Note that I am challenging myself with this 1 hour as I will have to put back the component used in geeks website and then neutralize the css and then add the needed classes that will allow us to style the component correctly. This component is quiet complicated and styling it to be designed like on sections website is not going to be straight forward
6 + 7) 0.25h

**Comment by mahfouzhseineweev** [comment]
> Clicking an Anchor is not copying the anchor, this is not specific to simple menu but as I wanted to copy one while working on it I added the point here

@akramsarkis For the Simple Menu section and the other ones, clicking the anchor is copying it just fine, if there is a way to reproduce it let me know

**Comment by akramsarkis** [comment]
> > Clicking an Anchor is not copying the anchor, this is not specific to simple menu but as I wanted to copy one while working on it I added the point here
> 
> @akramsarkis For the Simple Menu section and the other ones, clicking the anchor is copying it just fine, if there is a way to reproduce it let me know

@mahfouzhseineweev 

Access this site then edit the page and try to click on the anchor icon then paste , this is not working http://projectcnamenov.k8s-dev.geeks.solutions/

**Comment by akramsarkis** [comment]
Hello @mahfouzhseineweev ,

Please find below the points not done or not working as expected

**Points not done**

1)  For the Author details, if you add the social medias like I mentioned , the preview needs to be updated as well

2) For Author details : More of this the social media links aren't part of the author details vue section ( Ref to the one of Maiori ), because they are not there ?

3) Menu section

a) If for a menu I have chosen other when I hover on it on the vue mode there is not a hand showing it is a link which is
wrong

b) We need a hidden field that will be under a label Advanced that you can expand and when you expand it you will have possibility to enter options and for each one an attribute and its value, like for example target = _blank, check, do what is more appropriate to have it. Add a description for the Options field : For this one you asked why it is needed I explained that it is julien that requested it so have you checked with julien to not add it ?

4) When you have an interactive display section with video, you cannot drag and drop it, even if you try to move it , it remains to its place. It happens that sometime it moves but more often it remains to its place

**points not done correctly**

1) For the language menu I added  one with both translation and when I saved and checked the section I am seeing the french version which is wrong, i am speaking in the Home page  http://projectcnamenov.k8s-dev.geeks.solutions/, more of this why /i can;t switch the home page to french when I add /fr it is as if he wants to create a new page

**Comment by mahfouzhseineweev** [comment]
@akramsarkis 

1 & 2 ) Have you added the sections look css file to have the socials showing ? Also you keep on saying `if you add the social medias like I mentioned` what do you mean ? where you mentioned this and to who ?

3) a) This is not reproducible, if you inspect a link that is other or another link that is has a page selected. Both are <a> tag which are links and which will show hands on hover by default. You need to provide more details for this one

b) I will leave another comment to Julien mentioning this one

4) Also not reproducible, please to provide a way to reproduce it !!

5) Language point: /fr is a new page, the translation of the Home page is `/fr/` bit you should know this already!
Please put more details about what you saw and what you are expected. I checked this briefly and it seems working fine on your Home page

**Comment by mahfouzhseineweev** [comment]
> We need a hidden field that will be under a label Advanced that you can expand and when you expand it you will have possibility to enter options and for each one an attribute and its value, like for example target = _blank, check, do what is more appropriate to have it.
Add a description for the Options field

@jfayad I didn't get this one, we already have a management for the links that automatically handle the anchors, external links, internal links. So what is this for ? 

Also these options can not have dynamic keys, the keys like `target` has to be predefined and only the values can be dynamic

**Comment by akramsarkis** [comment]
> @akramsarkis
> 
> 1 & 2 ) Have you added the sections look css file to have the socials showing ? Also you keep on saying `if you add the social medias like I mentioned` what do you mean ? where you mentioned this and to who ?
> 
> 3. a) This is not reproducible, if you inspect a link that is other or another link that is has a page selected. Both are  tag which are links and which will show hands on hover by default. You need to provide more details for this one
> 
> b) I will leave another comment to Julien mentioning this one
> 
> 4. Also not reproducible, please to provide a way to reproduce it !!
> 5. Language point: /fr is a new page, the translation of the Home page is `/fr/` bit you should know this already!
>    Please put more details about what you saw and what you are expected. I checked this briefly and it seems working fine on your Home page


1) for 1 and 2 what I mean is  that by default the social media options should be there, not when selecting a css ,  at least this is what I saw when you added them on maiori, they where available when adding the section, am I wrong ?

2 a) /if you check on my site in the home page, there is no link in menu 2 that has an other link

3) for the interactive , as well check on my site i am just trying to move it and I am not able, there is no details to add there

4) Well for the language no I did not know but however if you check my site again, i added for french Fr as label and for english en and if you check the section it shows the contrary i have fr for english and english for fr

**Comment by jfayad** [comment]
> > We need a hidden field that will be under a label Advanced that you can expand and when you expand it you will have possibility to enter options and for each one an attribute and its value, like for example target = _blank, check, do what is more appropriate to have it.
> > Add a description for the Options field
> 
> @jfayad I didn't get this one, we already have a management for the links that automatically handle the anchors, external links, internal links. So what is this for ?
> 
> Also these options can not have dynamic keys, the keys like `target` has to be predefined and only the values can be dynamic

the management we have is different... this management is to give control to the webmaster

Why do you say that keys like target have to be predefined ? the whole purpose is to add these as additional options as attributes to the anchor tag (basically they will be read and added dynamically in the template of the component

**Comment by akramsarkis** [comment]
Feedbacks regarding the plans section @mahfouzhseineweev :

- [ ] We have all the labels without translations why ?  And this for any sections, we need to fix this

<img width="512" alt="Screenshot 2024-11-15 at 10 26 22" src="https://github.com/user-attachments/assets/cbfc2a33-ecfb-42c2-9a32-66c54878aca7">

**Comment by mahfouzhseineweev** [comment]
@akramsarkis Which sections did you notice that has not translations while you QAed other than the plans one ?

**Comment by akramsarkis** [comment]
> @akramsarkis Which sections did you notice that has not translations while you QAed other than the plans one ?

Hum when I tested first I noticed some but now I did a review and there is just the plans one

**Comment by mahfouzhseineweev** [comment]
> the management we have is different... this management is to give control to the webmaster

Why do you say that keys like target have to be predefined ? the whole purpose is to add these as additional options as attributes to the anchor tag (basically they will be read and added dynamically in the template of the component

Indeed, this could be possible using the v-bind attribute. Now I haven't tried this yet but I think it will work.
But this point along is ~1.25h update, is it possible that we ship this one in the next release update ? @jfayad

**Comment by jfayad** [comment]
> > All the uninstalled sections have no preview... why ? they should have
> 
> They are not just uninstalled from the project. They are also removed from the host project code, and so they have no forms or views. This is why they can not have a preview

wait a second, when you install them, their code is available, this means the code is in the host project as I know for a fact that nothing gets downloaded... so rely on these files.

The purpose of the preview is to let users know if they want to actually install the section on the project

**Comment by mahfouzhseineweev** [comment]
> wait a second, when you install them, their code is available, this means the code is in the host project as I know for a fact that nothing gets downloaded... so rely on these files.

@jfayad  Well I just thought the issue point reported is speaking about the sections that were deleted from the host project (the sections website ones) as after deleting them they were still showing the section types list.

Now I got the point which is about the preview of the sections inside the inventory which can be done and I have no remark about

**Comment by akramsarkis** [comment]
> > wait a second, when you install them, their code is available, this means the code is in the host project as I know for a fact that nothing gets downloaded... so rely on these files.
> 
> @jfayad Well I just thought the issue point reported is speaking about the sections that were deleted from the host project (the sections website ones) as after deleting them they were still showing the section types list.
> 
> Now I got the point which is about the preview of the sections inside the inventory which can be done and I have no remark about

Now preview are showing in the inventory as well

**Comment by akramsarkis** [comment]
@jfayad I saw a message in mattermost that you have still problem to move the interactive display section, but today I am searching it and not finding it, is it finally working ? If not can we open a separate issue for it ?

**Comment by jfayad** [comment]
> @jfayad I saw a message in mattermost that you have still problem to move the interactive display section, but today I am searching it and not finding it, is it finally working ? If not can we open a separate issue for it ?

I was on a prod. website, that's why I removed my message as we haven't published the fixes yet :-)

**Comment by akramsarkis** [comment]
ok so i will close this one
