### ISSUE TITLE
Adjustment of the Plan section to simplify it + glitches to fix

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-cli-plugin-sections#22]
<details>
<summary> Plans </summary>

- [ ] Rename Block 1, block 2 , etc to Plan 1, Plan 2 etc
- [ ] Media must be the first field in the top of the block
- [ ] Most popular and title  should be in the same line with most popular first, after the media
- [ ] Description must come after
- [ ] Currency and Price must in the same line with currency first, after the description
- [ ] Payment frequency should be after price and currency
- [ ] Link must be removed
- [ ] We need Custom feature to be added before features for any blocks and more of that there should be no condition to have it displayed
- [ ] Features should come after custom feature
- [ ] Start label must be renamed Plan CTA label, and there should no more be condition to have it displayed, here the  behavior
- If I filled the Plan CTA label this is the one that will be used with the Plan CTA link, if  I left it empty this is the global label that will be used
- [ ] We need  a description under the Plan CTA label field " If you keep this label empty, the global one will be used"
- [ ] Start link must be renamed Plan CTA link
- [ ] After the plans , the field page label must be removed
- [ ] Know more label must be renamed Global link label
- [ ] The labels should have the look of the global one with the arrow whatever label I am using

<img width="316" alt="Screenshot 2024-11-19 at 19 15 19" src="https://github.com/user-attachments/assets/082e962a-b3c7-4afb-b888-bf34a23b3072">

- [ ] Some points we noticed
- When I select most popular  while editing the section for the 4th block it is not applied
- The arrow for the first plan near the cta label is not showing , I need to hover to see it

</details>

<details>
<summary> Glitch to fix </summary>

- [ ] When I edit a section, do the scroll to the section automatically

</details>

### Acceptance testing

<details>
<summary> Plans </summary>

- [ ] Rename Block 1, block 2 , etc to Plan 1, Plan 2 etc
- [ ] Media must be the first field in the top of the block
- [ ] Most popular and title  should be in the same line with most popular first, after the media
- [ ] Description must come after
- [ ] Currency and Price must in the same line with currency first, after the description
- [ ] Payment frequency should be after price and currency
- [ ] Link must be removed
- [ ] We need Custom feature to be added before features for any blocks and more of that there should be no condition to have it displayed
- [ ] Features should come after custom feature
- [ ] Start label must be renamed Plan CTA label, and there should no more be condition to have it displayed, here the  behavior
- If I filled the Plan CTA label this is the one that will be used with the Plan CTA link, if  I left it empty this is the global label that will be used
- [ ] We need  a description under the Plan CTA label field " If you keep this label empty, the global one will be used"
- [ ] Start link must be renamed Plan CTA link
- [ ] After the plans , the field page label must be removed
- [ ] Know more label must be renamed Global link label
- [ ] The labels should have the look of the global one with the arrow whatever label I am using

<img width="316" alt="Screenshot 2024-11-19 at 19 15 19" src="https://github.com/user-attachments/assets/082e962a-b3c7-4afb-b888-bf34a23b3072">

- [ ] Some points we noticed
- When I select most popular  while editing the section for the 4th block it is not applied
- The arrow for the first plan near the cta label is not showing , I need to hover to see it

</details>

<details>
<summary> Glitch to fix </summary>

- [ ] When I edit a section, do the scroll to the section automatically

</details>

**Comment by jfayad** [comment]
@mahfouzhseineweev I tested the new Plans Sections with no custom css. 

I have the following feedbacks:

1. The => next to the CTA label is showing even if there's no label at all... it should not (we could have a plan with no link at all)
2. Remove the currency symbol field, we can input the currency inside the price field
3. Let's make the title not required anymore, if the title of a Plan is not there, we won't show the plan (and we will center the display of the plans). For example, if we only have 1 plan, it will be in the middle, if we have two, both will be centered etc... with a max. of 4 for now

**Comment by mahfouzhseineweev** [comment]
@jfayad 

For 2. Isn't it better to keep both fields as both have different styles ? I know it could be possible to style first char in the content different then the others but that will require more work on the CSS and it is not optimal

**Comment by jfayad** [comment]
> @jfayad
> 
> For 2. Isn't it better to keep both fields as both have different styles ? I know it could be possible to style first char in the content different then the others but that will require more work on the CSS and it is not optimal

Indeed, that makes sense, but then make sure they display on the same line (with the currency before the price)

**Comment by akramsarkis** [comment]
@mahfouzhseineweev  there 2 small feedbacks:

1) For title as it is no more required please to remove the *
2) For popular, I am not seeing anything till I apply the css,  we need to see even if there is no css that I selected it
