### ISSUE TITLE
When project is configured to use only french language, it is not applied on the plan section neither on FAQ section

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-cli-plugin-sections#27]
- [x] When from BO section you select only French language and you save then on the site you edit a section, there is only one language showing but the english one not the french one as even if french was selected, you are seeing the content you entered for english.

You can use still my account [a.sarkis+cnameprojectnov@eweev.com](mailto:a.sarkis+cnameprojectnov@eweev.com)/ Goldman31 and set for it the language to fr

- [x] Write automate test to handle this case

### Acceptance testing

- [x] When from BO section you select only French language and you save then on the site you edit a section, there is only one language showing but the english one not the french one as even if french was selected, you are seeing the content you entered for english.

You can use still my account [a.sarkis+cnameprojectnov@eweev.com](mailto:a.sarkis+cnameprojectnov@eweev.com)/ Goldman31 and set for it the language to fr

- [x] Write automate test to handle this case

**Comment by mahfouzhseineweev** [comment]
Estimate: 1h to 1.5h

Automated test:
* Write a test to make sure the form is showing in the correct language

**Comment by akramsarkis** [comment]
@mahfouzhseineweev I checked the sections and it is happening with FAQ as well

**Comment by akramsarkis** [comment]
@mahfouzhseineweev you make it for the plan section but not for the FAQ so you need to fix your automated test as well to check the FAQ one

**Comment by mahfouzhseineweev** [comment]
@akramsarkis Indeed, tbh with you I haven't noticed your recent comment and the change in the title so I didn't work on the FAQ one. This is a 10mn fix I will go for it now

**Comment by akramsarkis** [comment]
All good, closing
