### ISSUE TITLE
When selecting a preset for your project from BO section, the changes are not showing on the site

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-cli-plugin-sections#28]
- [x] When selecting a preset for your project from BO section, the changes are not showing on the site
- This needs adjustment on the css files of the preset 

- [x] Write automate test to cover the point

### Acceptance testing

- [x] When selecting a preset for your project from BO section, the changes are not showing on the site
- This needs adjustment on the css files of the preset 

- [x] Write automate test to cover the point

**Comment by mahfouzhseineweev** [comment]
@akramsarkis Can you put more details regarding what sections are not updating and what are the css styles that you are expecting to see for them ? In order to give a correct estimation

**Comment by mahfouzhseineweev** [comment]
@akramsarkis Here is the updated preset ENV variable that should be set on rancher dev ENV for Sections BO 

`NUXT_ENV_SECTIONS_CSS_PRESET=[{\"name\": \"Preset 1\", \"url\": \"https://s3.amazonaws.com/eweevtestbucketprivate/sections%2Fpreset+1b17fc59aaa98479793f4daf4d3cab9e1.css\"},{\"name\": \"Preset 2\", \"url\": \"https://s3.amazonaws.com/eweevtestbucketprivate/sections%2Fpreset+2b5b71a93498b46d3b1a37d718c512249.css\"},{\"name\": \"Preset 3\", \"url\": \"https://s3.amazonaws.com/eweevtestbucketprivate/sections%2F33dde5e53089e74d758bd0c03c37c08b13.css\"}]`

**Comment by akramsarkis** [comment]
> @akramsarkis Here is the updated preset ENV variable that should be set on rancher dev ENV for Sections BO
> 
> `NUXT_ENV_SECTIONS_CSS_PRESET=[{\"name\": \"Preset 1\", \"url\": \"https://s3.amazonaws.com/eweevtestbucketprivate/sections%2Fpreset+1b17fc59aaa98479793f4daf4d3cab9e1.css\"},{\"name\": \"Preset 2\", \"url\": \"https://s3.amazonaws.com/eweevtestbucketprivate/sections%2Fpreset+2b5b71a93498b46d3b1a37d718c512249.css\"},{\"name\": \"Preset 3\", \"url\": \"https://s3.amazonaws.com/eweevtestbucketprivate/sections%2F33dde5e53089e74d758bd0c03c37c08b13.css\"}]`

@mahfouzhseineweev do I need to upload new files on my medias library ?  If you need to provide to me the updated files
